FPS = 60

GAMESCREEN_WIDTH = 1220
GAMESCREEN_HEIGHT = 725

INDENT_UP = 50
INDENT_SIDE = 100
INDENT_BOTTOM = 175
LOWER_LINE = 500

GAMEFIELD_WIDHT = GAMESCREEN_WIDTH - INDENT_SIDE * 2 + 4
GAMEFIELD_HEIGHT = LOWER_LINE + 150
LEVEL_COUNT_WIDTH = 30  # 34
LEVEL_COUNT_HEIGHT = 25

BALL_RADIUS = 6

BRICK_WIDTH = 30  # 30
BRICK_HEIGHT = 15
INDENT_HORIZONTAL_BRICK = 4
INDENT_VERTICAL_BRICK = 5

PADDLE_WIDTH = 100
PADDLE_HEIGHT = 15

BRICK_COLORS = [
    "assets/brick.png",
    "assets/brick2.png",
    "assets/brick3.png",
    "assets/brick4.png",
    "assets/brick5.png"
]


